name: Build and Test

on:
  pull_request:
    branches:
      - "*"

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Format code
        uses: actions-rs/rustfmt@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust-version: [stable, beta]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust-version }}

      - name: Build and test
        run: cargo build --verbose && cargo test --verbose

      - name: Code analysis
        run: cargo clippy --all-targets --all-features -- -D warnings